# Generated by Django 3.1.2 on 2020-10-15 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_weather'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weather',
            name='api_key',
        ),
    ]
