# Generated by Django 3.1.2 on 2020-10-15 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0003_remove_weather_api_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecureData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=50)),
                ('api_key', models.CharField(max_length=200)),
            ],
        ),
    ]
